http_port 3128
acl localnet dst 10.0.0.0/8
acl localnet dst 100.64.0.0/10
acl localnet dst 127.0.0.0/8
acl localnet dst 169.254.0.0/16
acl localnet dst 172.16.0.0/12
acl localnet dst 192.168.0.0/16
acl localnet dst fc00::/7
acl localnet dst fe80::/10
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny localnet
http_access allow all
via off
forwarded_for delete
request_header_access Authorization deny all
cache deny all
access_log stdio:/var/log/squid/access.log
